### ISSUE TITLE
fetch_coefficients broken

### ISSUE THREAD

**Issue by drmkaul** [Dih5/physdata#3]
Haven't run my program in a month or so. Used to work fine. Now i get the following error:

  File "<ipython-input-25-5cada296cc2f>", line 11, in <module>
    data = np.array(fetch_coefficients(Z))

  File "C:\\anaconda3\lib\site-packages\physdata\xray.py", line 152, in fetch_coefficients
    html = str(html).split("</DIV>")[2]  # Pick the div with the ascii table

IndexError: list index out of range

**Comment by drmkaul** [comment]
Wait, i just figured out that it's because of the govt shutdown!

**Comment by Dih5** [comment]
Nonetheless, thank you for posting the issue: I have added less confusing errors and warnings (75e7b748bc042792d21ac206ea6cf61273a25161). I will make a release when the website is up again.
